--create table Employee (eid integer generated by default as identity, deg varchar(255), ename varchar(255), salary double, primary key (eid))

insert into Employee values (default,'Technical Manager', 'Gopal', 40000);
insert into Employee values (default,'Proof reader', 'Manisha', 40000);
insert into Employee values (default,'Technical Writer', 'Masthanvali', 40000);
insert into Employee values (default,'Technical Writer', 'Satish', 30000);
insert into Employee values (default,'Technical Writer', 'Krishna', 30000);
insert into Employee values (default,'Proof reader', 'Kiran', 35000);